# Generated by Django 5.0.2 on 2024-02-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_image_url_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('UNLISTED', 'UNLISTED'), ('FRIENDS', 'FRIENDS')], default='PUBLIC', max_length=10),
        ),
    ]
