# Generated by Django 5.0.2 on 2024-02-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(default='default_image_url', max_length=200),
        ),
    ]
