# Generated by Django 5.0.2 on 2024-03-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_merge_20240316_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='localhost:8000/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/markdown', max_length=50),
        ),
    ]
