# Generated by Django 5.0.2 on 2024-03-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_comment_author_likepost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='username',
        ),
    ]
