# Generated by Django 5.0.2 on 2024-03-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_alter_comment_date_added_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_markdown',
            field=models.TextField(blank=True, default=''),
        ),
    ]
