# Generated by Django 5.0.2 on 2024-02-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
