# Generated by Django 5.0.2 on 2024-03-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
