# Generated by Django 5.0.2 on 2024-02-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]