# Generated by Django 5.0.2 on 2024-02-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_image',
        ),
    ]
