# Generated by Django 5.0.2 on 2024-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profileimg',
            new_name='profileImage',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=6),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
