# Generated by Django 5.0.2 on 2024-02-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_rename_profileimg_author_profileimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='url',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_image'),
        ),
    ]
