# Generated by Django 5.0.1 on 2024-02-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_rename_url_author_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_image',

        ),
    ]
