# Generated by Django 5.0.2 on 2024-02-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_remove_author_profileimage_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='is_friend',
        ),
    ]
