# Generated by Django 5.0.1 on 2024-02-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_remove_author_profileimage'),
        ('authors', '0009_follower_is_friend'),
    ]

    operations = [
    ]
