# Generated by Django 5.0.1 on 2024-02-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_merge_20240224_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
