# Generated by Django 5.0.2 on 2024-02-25 21:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_author_host_author_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c63a0ac5-cd38-4ad3-a02a-3fd4f948bbb0'), editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
