# Generated by Django 5.0.2 on 2024-02-26 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0016_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b53e65f8-f1f3-4033-a1b9-17fffb0d0b83'), editable=False, max_length=50, unique=True),
        ),
    ]
