# Generated by Django 5.0.2 on 2024-02-26 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0019_alter_author_host_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1f0b118b-0183-4c65-a322-c586f438d342'), editable=False, max_length=50, unique=True),
        ),
    ]
