# Generated by Django 5.0.2 on 2024-02-27 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0022_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ac720e8d-df32-4b24-a5ba-ac825d169611'), editable=False, max_length=50, unique=True),
        ),
    ]
