# Generated by Django 5.0.2 on 2024-02-27 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0024_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('af0fa5e8-2ac4-4783-9258-ba80f5c87120'), editable=False, max_length=50, unique=True),
        ),
    ]
