# Generated by Django 5.0.2 on 2024-02-28 03:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0025_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d5d08350-72e1-4241-aac9-a6d76d91facf'), editable=False, max_length=50, unique=True),
        ),
    ]
