# Generated by Django 5.0.2 on 2024-02-28 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0027_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cecacfeb-eb03-48c3-a8fe-b700d18e30b7'), editable=False, max_length=50, unique=True),
        ),
    ]
