# Generated by Django 5.0.2 on 2024-02-28 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0028_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('69521a86-6f16-42b0-a3c2-37bd7eacaf73'), editable=False, max_length=50, unique=True),
        ),
    ]
