# Generated by Django 5.0.2 on 2024-02-28 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0029_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f3223cc6-5b76-4112-bdc0-3d2beb6e8fd5'), editable=False, max_length=50, unique=True),
        ),
    ]
