# Generated by Django 5.0.2 on 2024-02-28 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0031_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2bf41e9a-6313-4f7c-80f1-27ed2c85ffb3'), editable=False, max_length=50, unique=True),
        ),
    ]
