# Generated by Django 5.0.2 on 2024-02-28 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0032_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bd1f619b-f48a-4e5e-8812-656d459662ed'), editable=False, max_length=50, unique=True),
        ),
    ]
