# Generated by Django 5.0.2 on 2024-02-28 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0033_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1a9cc78c-82c1-41c5-a4f0-ca30e3a194e1'), editable=False, max_length=50, unique=True),
        ),
    ]
