# Generated by Django 5.0.2 on 2024-02-29 05:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0034_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ab8a80fa-e0a1-48a1-82ed-445e8c488a83'), editable=False, max_length=50, unique=True),
        ),
    ]
