# Generated by Django 5.0.2 on 2024-03-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0036_alter_author_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
