# Generated by Django 5.0.2 on 2024-03-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0037_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='url',
            new_name='host',
        ),
    ]
