# Generated by Django 5.0.2 on 2024-03-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0038_rename_url_node_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
    ]
