# Generated by Django 5.0.2 on 2024-03-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0039_remove_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
