# Generated by Django 5.0.2 on 2024-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0040_node_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
