# Generated by Django 5.0.2 on 2024-03-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0041_alter_node_host_alter_node_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
