# Generated by Django 5.0.2 on 2024-03-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0042_alter_node_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='api_prefixed',
            field=models.BooleanField(default=False),
        ),
    ]
