# Generated by Django 5.0.2 on 2024-03-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0043_node_api_prefixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.URLField(),
        ),
    ]
